### ISSUE TITLE
Red Guy Talk After Death

### ISSUE THREAD

**Issue by maddiemccay** [coopersully/ducktective#11]
**Describe the bug.**
You can talk to the red guy even after you kill him.

**To Reproduce**

**Expected behavior**
You shouldnt be able to talk to him.

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.0-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this issue is fixed in `v1.1-ALPHA`.
