### ISSUE TITLE
Red duck not falling after death.

### ISSUE THREAD

**Issue by maddiemccay** [coopersully/ducktective#14]
**Describe the bug.**
Sometimes after you kill the red duck, he stays for a couple of seconds and then just disapears.

**To Reproduce**

**Expected behavior**

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.0-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this issue is fixed in `v1.1-ALPHA`.
