### ISSUE TITLE
Buying Tickets at Meemaw's

### ISSUE THREAD

**Issue by maddiemccay** [coopersully/ducktective#15]
**Describe the bug.**
You have to walk out of meemaw's store and back in again in order to buy a ticket even if you have enough money.

**To Reproduce**

**Expected behavior**
You should be able to just buy a ticket if you have enough money.

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.0-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this issue is fixed in `v1.7-ALPHA`.
