### ISSUE TITLE
Text Box Lines

### ISSUE THREAD

**Issue by maddiemccay** [coopersully/ducktective#17]
**Describe your idea.**
For the text boxes under the submit a ticket page, the text continues on one line and i think it should go down, that way you can see your entire message.

**Is your feature request related to a problem? Please describe.**

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.0-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this feature is now added in `v1.7-ALPHA`.
