### ISSUE TITLE
pause game issue

### ISSUE THREAD

**Issue by chilimoke** [coopersully/ducktective#19]
**Describe the bug.**
If I stop to check my stats mid game and I go back to the game I swing and it counts as a missed swing. As I'm tpying this everytime I press space a sound effect comes up and also when I click then press space It sounds like I'm swinging.

**To Reproduce**

**Expected behavior**
No sound effects while paused and don't swing after unpausing.

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.7-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this issue is fixed in `v1.8-ALPHA`.
