### ISSUE TITLE
death bug

### ISSUE THREAD

**Issue by chilimoke** [coopersully/ducktective#21]
**Describe the bug.**
When you die you can still hit people during the timer

**To Reproduce**

**Expected behavior**
hitting should be disabled during the death timer

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.7-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this issue is fixed in `v1.8-ALPHA`.
