### ISSUE TITLE
Game Completion Timer

### ISSUE THREAD

**Issue by maddiemccay** [coopersully/ducktective#7]
**Describe the bug.**
At the end of them game, when it tells you your stats once youve completed the game, it doesnt tell you the correct time that it took you to finish the game.

**To Reproduce**

**Expected behavior**
Records how long it took you to finish the game.

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.0-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this issue is now fixed in `v1.1-ALPHA`.
