### ISSUE TITLE
Inverted mouse

### ISSUE THREAD

**Issue by maddiemccay** [coopersully/ducktective#8]
**Describe your idea.**
The ability to not use an invert mouse.

**Is your feature request related to a problem? Please describe.**
Inverted mouse is not easy for everyone to use.

**Computer & Game Specifications**
- Operating System: Microsoft Windows NT 10.0.19044.0
- Game Version: v1.0-ALPHA

**Additional context**

**Comment by coopersully** [comment]
Thanks for the feedback; this feature is now added in `v1.1-ALPHA`.
